# copy to clipboard when selecting using mouse
[selection]
save_to_clipboard = true

# set to dark theme
[window]
decorations_theme_variant = "Dark"

# after copy, exit vi mode automatically
[keyboard]
bindings = [
  {key = "Y", mode = "Vi|~Search", action = "Copy"},
  {key = "Y", mode = "Vi|~Search", action = "ToggleViMode"},
]
